create table entry_info (
    entry_id integer auto_increment,
    req_date varchar(8),
    entry_date varchar(8),
    entry_time_s integer(2),
    entry_time_e integer(2),
    req_user varchar(5),
    req_group varchar(2),
    entry_user1 varchar(5),
    entry_user2 varchar(5),
    entry_user3 varchar(5),
    entry_user4 varchar(5),
    entry_user5 varchar(5),
    req_reason varchar(1000),
    remark varchar(1000),
    status varchar(1),
    conform_user1 varchar(5),
    conform_user2 varchar(5),
    conform_user3 varchar(5),
    primary key (entry_id,req_date)
);
